version: '3.9'
services:
  db-mariadb:
    restart: always
    image: mariadb:11.0.2
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=${DB_USR}
      - MARIADB_PASSWORD=${DB_PWD}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_SCHEMA}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./vol/db:/va/lib/mysql
  financer:
    restart: always
    build: .
    depends_on:
      - db-mariadb
    ports:
      - '${PORT}:8000'
    links:
      - db-mariadb
    environment:
      - DOCKER=YES
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USR=${DB_USR}
      - DB_PWD=${DB_PWD}
