version: '3.9'
services:
  db-mariadb:
    restart: always
    image: mariadb:11.0.2
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - db-mariadb01:/va/lib/mysql
  financer:
    restart: always
    build: .
    ports:
      - '${PORT}:${PORT}'
    links:
      - db-mariadb
    environment:
      - DOCKER=YES
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USR=${DB_USR}
      - DB_PWD=${DB_PWD}
  
volumes:
  db-mariadb01: